messages:
  JoinMessage: "§b%player_name% §ahas joined the game"
  LeaveMessage: "§b%player_name% §cleft the game"
  DeathMessage: "§b%player_name% §cdied!"
defaultRole: player
defaultWorld: world
loadAllWorlds: true
maxWarpListLength: 20
messagingLevel: DEBUG
reservedWarpNames:
  - "create"
  - "top"
  - "list"