name: ServerManager_v2
version: '1.0-SNAPSHOT'
main: de.sdrs.servermanager_v2.plugin.main.ServerManager
api-version: '1.20'
load: STARTUP
authors: [SDRS]
softdepend:
  - PlaceholderAPI
commands:
  servermanager:
    description: gives some help
    usage: /servermanager
    aliases:
      - sm
  player:
    description: some useful commands to edit players
    usage: /player {playerName}
  role:
    description: some useful role commands
    usage: /role
  world:
    description: some useful world tools
    usage: /world {args}
  warp:
    description: some useful warp tools
    usage: /warp {args}
