name: ServerManager_v2
version: '1.0-SNAPSHOT'
main: de.sdrs.servermanager_v2.plugin.main.ServerManager
api-version: '1.20'
load: STARTUP
authors: [SDRS]
softdepend:
  - PlaceholderAPI
commands:
  test:

  test2:

